# This is a basic workflow to help you get started with Actions

name: One Piece Manga Datastore 

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch latest available One Piece manga
        uses: docker://minormending/viz-manga:latest
        with:
          args: 
            fetch
            one-piece
            --directory=.
      
      - name: Setup GitHub user
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      
      - name: Commit the chapters
        run: |
          git status
          git add .
          git commit -m "Auto fetching latest One Piece chapters."
          
      - run: git push origin HEAD:main
        
