# This is a basic workflow to help you get started with Actions

name: One Piece Manga Datastore 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Run a one-line script
        uses: docker://minormending/viz-manga:latest
        with:
          args: 
            fetch
            24297
            --directory=.
        
      - name: Check status
        run: git status
      - name: Add files
        run: git add .
        
