# This is a basic workflow to help you get started with Actions

name: One Piece Manga Datastore 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        uses: docker://minormending/viz-manga:latest
        with:
          args: series
        
